repos:
  - repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
      - id: black
        language_version: python3.13
        args: ["--line-length", "88"]
  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort
        language_version: python3.13
        args: [
          "--profile", "black",
          "--line-length", "88"
        ]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        language_version: python3.13
        args: [
          "--max-line-length", "88",
          "--extend-ignore", "E203,W503",
          "--exclude", "__init__.py"
        ]
  # Runs a hook that installs poetry dependencies in mypy venv
  - repo: local
    hooks:
      - id: mypy-per-service
        name: mypy per service
        language: script
        entry: ./scripts/mypy_hook.sh
        types: [python]
        pass_filenames: true
        require_serial: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
